ssh_keys: &ssh_keys
  - "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJf+OIwp58UAZgSAJfgtN5tOoXvSuTiAUFCHYX6DhwvyAAAAEXNzaDpnZW5pZF9wcmltYXJ5 ssh:genid_primary"
  - "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILSkO987357FNA/ptWc9ShOdMWLdcL8/yev0xj1zUDxHAAAAEXNzaDpzZWNpZF9wcmltYXJ5 ssh:secid_primary"
git_config: &git_config
  name: "149segolte"
  email: &git_email "37300847+149segolte@users.noreply.github.com"
  sign:
    format: "ssh"
    key: ".ssh/id_ed25519_sk.pub"
    allowed_signers:
      location: ".ssh/git_allowed_signers"
      entries:
        - email: *git_email
          keys: *ssh_keys
fish_config: &fish_config
  config:
    manual_config: |
      tide configure
  fisher:
    plugins:
      - "patrickf1/fzf.fish"
      - "ilancosman/tide@v6"
hosts:
  novasking:
    ssh:
      keys: *ssh_keys
      output_pubs: true
    git: *git_config
    fish:
      <<: *fish_config
      switch_shell: "bash"
  rpi:
    ssh:
      keys: *ssh_keys
    git: *git_config
    fish:
      <<: *fish_config
      switch_shell: "bash"
  yigirus:
    ssh:
      keys: *ssh_keys
      output_pubs: true
    git:
      <<: *git_config
      global_exclude:
        location: ".gitignore_global"
        entries:
          - ".DS_Store"
    fish:
      <<: *fish_config
      switch_shell: "zsh"
