ssh_keys: &ssh_keys
  - "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJf+OIwp58UAZgSAJfgtN5tOoXvSuTiAUFCHYX6DhwvyAAAAEXNzaDpnZW5pZF9wcmltYXJ5 ssh:genid_primary"
  - "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILSkO987357FNA/ptWc9ShOdMWLdcL8/yev0xj1zUDxHAAAAEXNzaDpzZWNpZF9wcmltYXJ5 ssh:secid_primary"
hosts:
  novasking:
    ssh:
      keys: !flatten
        - *ssh_keys
      output_pubs: true
      host_declarations: true
  rpi:
    ssh:
      keys: !flatten
        - *ssh_keys
  yigirus:
    ssh:
      keys: !flatten
        - *ssh_keys
      output_pubs: true
      host_declarations: true
