# Load all module tasks here
---
- name: "Import SSH module tasks"
  ansible.builtin.import_tasks: ssh.yaml
  tags: modules,ssh
- name: "Import Git module tasks"
  ansible.builtin.import_tasks: git.yaml
  tags: modules,git
