github:
  user: "149segolte"
  email: "37300847+149segolte@users.noreply.github.com"
packages:
  darwin:
    brews: []
    casks: []
  linux:
    flatpaks:
      - flatseal
    fedora:
      package_manager: dnf
      exclude_flag: "--exclude="
      update_check: "dnf check-update -q | wc -l"
      cli:
        common:
          - fish
          - git
          - neovim
          - "-nodejs"
          - btop
          - bat
          - zoxide
          - ripgrep
          - fzf
          - fd-find
          - du-dust
          - tmux
